brand:
  name:
  - infima
  - "&lt;"
  - labs
  intro:
    heading:
    - Experience all realities
  speedball:
    heading: GRIT Paintball
    subheading: Tournament Paintball Trainer and Simulator
    stories:
    - img: img/grit.jpg
      alt: Looking to gain an edge in the real game?
      include: grit.md
  connect:
    heading: Want More?
    subheading: >-
      Play GRIT&nbsp;Paintball&trade;
  social:
  - title: facebook
    url: https://www.facebook.com/infimalabs
  - title: instagram
    url: https://www.instagram.com/infimalabs/
  - title: twitter
    url: https://twitter.com/infimalabs
  - title: tiktok
    url: https://www.tiktok.com/@infimalabs
  - title: github
    url: https://github.com/infimalabs
nav:
- title: GRIT
  url: '#speedball'
- title: Connect
  url: '#connect'
copyright: Infima Labs
