copyright: Infima Labs

ident:
  ga: G-9MZFEVF7HW
  sleekplan: "967750792"

brand:
  name:
  - infima
  - "&lt;"
  - labs
  social:
  - title: facebook
    url: https://www.facebook.com/infimalabs
  - title: instagram
    url: https://www.instagram.com/infimalabs/
  - title: twitter
    url: https://twitter.com/infimalabs

nav:
- title: GRIT
  url: '/#grit-paintball'
- title: SPACE
  url: '/#infima-space'
- title: Updates
  url: '/updates'
- title: Feedback
  url: '/feedback'
