brand:
  name:
  - infima
  - "&lt;"
  - labs
  intro:
    heading:
    - V is for Visceral
  speedball:
    heading: GRIT Paintball
    subheading: Tournament Paintball Trainer and Simulator
    stories:
    - img: img/grit.jpg
      alt: Looking to gain an edge in the real game?
      include: grit.md
  connect:
    heading: Want More?
    subheading: >-
      Play GRIT&nbsp;Paintball&trade;
nav:
- title: GRIT
  url: '#speedball'
- title: Connect
  url: '#connect'
copyright: |-
  &copy;&nbsp;**2022** Infima Labs
